### ISSUE TITLE
force-torque sensor for haptic feedback

### ISSUE THREAD

**Issue by shivanimall** [stanford-iprl-lab/multimodal_representation#25]
I am wondering is there a reason for using SAI 2.0 for simulation and haptic feedback vs the more popular physics engines (such as mujoco) and their built-in force-torque feedback in that?

many thanks for your help!

**Comment by jbohg** [comment]
The reason was that the simulated force feedback from SAI 2.0 has much higher fidelity
Best, Jeannette

**Comment by shivanimall** [comment]
Many thanks Jeannette for your help
