### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by CCG121** [stanford-iprl-lab/multimodal_representation#29]
When I run the program, the following error is reported. Do you know what the problem is? 

File "\home\downloads\multimodal_representation\multimodal\mini_main.py", line 20, in <module>
    with open(args.config) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by amichlee** [comment]
Looks like you didn't give it the config file path (which is why it's complaining it's a NoneType).

Try running this: 
`python mini_main.py --config configs/training_default.yaml` ?
